# Netlify configuration for see_pdfeditor
# Enhanced security configuration

[build]
  # No build command needed - static site
  publish = "production-build"

  # Build settings
  command = "echo 'No build required - static site'"

# Enhanced Security headers - applied to all requests
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy - Strict but functional
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdn.jsdelivr.net https://cdn.tailwindcss.com https://www.googletagmanager.com https://www.google-analytics.com 'unsafe-inline' 'unsafe-eval'; style-src 'self' https://cdn.jsdelivr.net https://cdn.tailwindcss.com 'unsafe-inline'; img-src 'self' data: blob: https:; connect-src 'self' https://cdn.jsdelivr.net https://www.google-analytics.com https://analytics.google.com data: blob:; font-src 'self' https://cdn.jsdelivr.net; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'self'; worker-src 'self' blob:;"

    # Clickjacking protection
    X-Frame-Options = "SAMEORIGIN"

    # MIME type sniffing protection
    X-Content-Type-Options = "nosniff"

    # XSS protection
    X-XSS-Protection = "1; mode=block"

    # Referrer policy for privacy
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Browser feature restrictions
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()"

    # Enable HSTS (HTTP Strict Transport Security)
    # Only enable after HTTPS is confirmed working
    # Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

    # Cache control for HTML
    Cache-Control = "public, max-age=3600, must-revalidate"

# JavaScript files - longer cache with fingerprinting
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# CSS files - longer cache with fingerprinting
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML files - shorter cache
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirect rules (if needed)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Environment variables (if needed)
# [build.environment]
#   NODE_VERSION = "18"
