name: Docs Lint

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run markdownlint (npx)
        run: |
          npx markdownlint-cli@0.33.0 "docs/**/*.md" --config .markdownlint.json
